name: S3UploadWorkflow

on:
  push:
    branches: [develop]

jobs:
  deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetupNode
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: SetupAws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload
        env:
          S3_BUCKET_URI: ${{ secrets.AWS_S3_UPLOAD_URI }}
          GET_ARTICLE_BY_ID: GetArticleById
          PUT_ARTICLE_BY_ID: PutArticleById
          DELETE_ARTICLE_BY_ID: DeleteArticleById
          GET_ARTICLES: GetArticles
          POST_ARTICLES: PostArticles
        run: |
          # GetArticleById
          cd $GET_ARTICLE_BY_ID &&
          yarn install &&
          zip $GET_ARTICLE_BY_ID node_modules/* index.js &&
          aws s3 mv $GET_ARTICLE_BY_ID.zip $S3_BUCKET_URI

          # PutArticleById
          cd $PUT_ARTICLE_BY_ID &&
          yarn install &&
          zip $PUT_ARTICLE_BY_ID node_modules/* index.js &&
          aws s3 mv $PUT_ARTICLE_BY_ID.zip $S3_BUCKET_URI

          # DeleteArticleById
          cd $DELETE_ARTICLE_BY_ID &&
          yarn install &&
          zip $DELETE_ARTICLE_BY_ID node_modules/* index.js &&
          aws s3 mv $DELETE_ARTICLE_BY_ID.zip $S3_BUCKET_URI

          # GetArticles
          cd $GET_ARTICLES &&
          yarn install &&
          zip $GET_ARTICLES node_modules/* index.js &&
          aws s3 mv $GET_ARTICLES.zip $S3_BUCKET_URI

          # PostArticles
          cd $POST_ARTICLES &&
          yarn install &&
          zip $POST_ARTICLES node_modules/* index.js &&
          aws s3 mv $POST_ARTICLES.zip $S3_BUCKET_URI
