name: S3UploadWorkflow

on:
  push:
    branches: [develop]

jobs:
  deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetupNode
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: SetupAws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload
        env:
          S3_BUCKET_URI: ${{ secrets.AWS_S3_UPLOAD_URI }}
          GET_ARTICLE_BY_ID: GetArticleById
          PUT_ARTICLE_BY_ID: PutArticleById
          DELETE_ARTICLE_BY_ID: DeleteArticleById
          GET_ARTICLES: GetArticles
          POST_ARTICLES: PostArticles
        run: |
          # GetArticleById
          cd $GET_ARTICLE_BY_ID &&
          yarn install &&
          zip -r $GET_ARTICLE_BY_ID node_modules index.js &&
          aws lambda update-function-code --function-name $GET_ARTICLE_BY_ID --zip-file fileb://$PWD/$GET_ARTICLE_BY_ID.zip > /dev/null 2>&1
          cd ..

          # PutArticleById
          cd $PUT_ARTICLE_BY_ID &&
          yarn install &&
          zip -r $PUT_ARTICLE_BY_ID node_modules index.js &&
          aws lambda update-function-code --function-name $PUT_ARTICLE_BY_ID --zip-file fileb://$PWD/$PUT_ARTICLE_BY_ID.zip > /dev/null 2>&1
          cd ..

          # DeleteArticleById
          cd $DELETE_ARTICLE_BY_ID &&
          yarn install &&
          zip -r $DELETE_ARTICLE_BY_ID node_modules index.js &&
          aws lambda update-function-code --function-name $DELETE_ARTICLE_BY_ID --zip-file fileb://$PWD/$DELETE_ARTICLE_BY_ID.zip > /dev/null 2>&1
          cd ..

          # GetArticles
          cd $GET_ARTICLES &&
          yarn install &&
          zip -r $GET_ARTICLES node_modules index.js &&
          aws lambda update-function-code --function-name $GET_ARTICLES --zip-file fileb://$PWD/$GET_ARTICLES.zip > /dev/null 2>&1
          cd ..

          # PostArticles
          cd $POST_ARTICLES &&
          yarn install &&
          zip -r $POST_ARTICLES node_modules index.js &&
          aws lambda update-function-code --function-name $POST_ARTICLES --zip-file fileb://$PWD/$POST_ARTICLES.zip > /dev/null 2>&1
          cd ..
