name: S3UploadWorkflow

on:
  push:
    branches: [develop]

jobs:
  deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetupNode
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: SetupAws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-acccess-key-id: ${{ secrets.AWS_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_USER_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload
        env:
          S3_BUCKET_URI: ${{ secrets.AWS_S3_UPLOAD_URI }}
        run: ls

